name: flutter_mcp_server
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.2

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  dotenv: ^4.1.0
  mcp_server: ^0.1.7
  logger: ^2.0.2

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
